###############
IMG:
  TYPE: 'png'  # 'jpg' , '' , ...

PATH:
  INPUT_DIR: './imgs'
  SAVE_DIR: './results'

CROP:
  NUMBER: 2       # total cropping patch number
  RANDOM: False    # True, False: crop the patches by random select
  POSITION: 'R'   # 'L'(eft), 'R'(ight), 'T'(op), 'B'(ottom)
  BOX_SIZES: 50   # the size of boundary box (pixel * pixel)
  BOX_THICK: 1    # thickness of boundary box (pixel)
  BOX_LOCAT: [[100, 100], [250, 250]]        # the pixel location of top-left corner [y, x]
  BOX_COLOR: [[0, 0, 255], [0, 255, 0]]  # the color of boundary box [B, G, R]
